FROM golang:1.22.4-alpine3.20 as builder

LABEL maintainer="Samuel Jirenius <samuel@jirenius.com>"

ENV GO111MODULE=on

WORKDIR /src/resgate

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -ldflags "-s -w" -o /resgate

FROM alpine:3.20
COPY --from=builder /resgate /bin/resgate

EXPOSE 8080

ENTRYPOINT ["/bin/resgate"]
CMD [""]
